job_id: tree-pruner-4b6d0ef5-b130-45d6-ae22-94fd7213f820
email: cct663@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Pipilo_aberti, Spizella_arborea, Amphispiza_bilineata, Sula_nebouxii, Luscinia_svecica,
  Fringilla_montifringilla, Molothrus_aeneus, Cinclus_pallasii, Cettia_diphone, Campylorhynchus_brunneicapillus,
  Daption_capense, Spizella_passerina, Fringilla_coelebs, Toxostoma_curvirostre, Junco_hyemalis,
  Pipilo_erythrophthalmus, Motacilla_flava, Passer_montanus, Phalacrocorax_harrisi,
  Zenaida_galapagoensis, Spheniscus_mendiculus, Pygoscelis_papua, Zonotrichia_atricapilla,
  Dendroica_graciae, Fregata_minor, Hemignathus_virens, Carpodacus_mexicanus, Passer_domesticus,
  Vestiaria_coccinea, Columbina_inca, Aptenodytes_patagonicus, Calcarius_lapponicus,
  Geospiza_conirostris, Alle_alle, Carpodacus_purpureus, Phalaropus_fulicarius, Sula_sula,
  Agelaius_phoeniceus, Carduelis_flammea, Zonotrichia_capensis, Passerculus_sandwichensis,
  Calidris_pusilla, Geospiza_difficilis, Geospiza_fuliginosa, Calcarius_pictus, Plectrophenax_nivalis,
  Melospiza_melodia, Cyphorhinus_phaeocephalus, Oceanodroma_tethys, Zonotrichia_leucophrys,
  Montifringilla_taczanowskii, Zenaida_asiatica, Pycnonotus_goiavier, Fratercula_arctica,
  Halobaena_caerulea, Mimus_parvulus, Pelecanoides_georgicus, Lugensa_brevirostris,
  Geospiza_magnirostris, Geospiza_fortis, Montifringilla_ruficollis]
sample_trees: [EricsonStage2Full_4346.tre, EricsonStage2Full_2979.tre, EricsonStage2Full_0301.tre,
  EricsonStage2Full_9613.tre, EricsonStage2Full_7893.tre, EricsonStage2Full_0059.tre,
  EricsonStage2Full_7628.tre, EricsonStage2Full_3505.tre, EricsonStage2Full_7419.tre,
  EricsonStage2Full_1956.tre, EricsonStage2Full_1614.tre, EricsonStage2Full_0782.tre,
  EricsonStage2Full_8806.tre, EricsonStage2Full_1891.tre, EricsonStage2Full_2024.tre,
  EricsonStage2Full_6839.tre, EricsonStage2Full_1776.tre, EricsonStage2Full_6577.tre,
  EricsonStage2Full_5995.tre, EricsonStage2Full_0431.tre, EricsonStage2Full_5435.tre,
  EricsonStage2Full_2752.tre, EricsonStage2Full_3111.tre, EricsonStage2Full_2309.tre,
  EricsonStage2Full_6591.tre, EricsonStage2Full_6842.tre, EricsonStage2Full_4613.tre,
  EricsonStage2Full_1662.tre, EricsonStage2Full_3276.tre, EricsonStage2Full_4017.tre,
  EricsonStage2Full_9703.tre, EricsonStage2Full_5073.tre, EricsonStage2Full_0772.tre,
  EricsonStage2Full_0259.tre, EricsonStage2Full_6513.tre, EricsonStage2Full_6919.tre,
  EricsonStage2Full_4991.tre, EricsonStage2Full_7070.tre, EricsonStage2Full_3434.tre,
  EricsonStage2Full_0130.tre, EricsonStage2Full_9116.tre, EricsonStage2Full_5714.tre,
  EricsonStage2Full_3880.tre, EricsonStage2Full_7634.tre, EricsonStage2Full_3793.tre,
  EricsonStage2Full_3081.tre, EricsonStage2Full_4870.tre, EricsonStage2Full_8500.tre,
  EricsonStage2Full_2789.tre, EricsonStage2Full_2948.tre, EricsonStage2Full_1313.tre,
  EricsonStage2Full_8050.tre, EricsonStage2Full_0039.tre, EricsonStage2Full_4380.tre,
  EricsonStage2Full_9767.tre, EricsonStage2Full_9660.tre, EricsonStage2Full_2206.tre,
  EricsonStage2Full_6782.tre, EricsonStage2Full_8010.tre, EricsonStage2Full_1515.tre,
  EricsonStage2Full_3172.tre, EricsonStage2Full_8869.tre, EricsonStage2Full_6830.tre,
  EricsonStage2Full_6575.tre, EricsonStage2Full_7633.tre, EricsonStage2Full_4322.tre,
  EricsonStage2Full_1863.tre, EricsonStage2Full_0188.tre, EricsonStage2Full_9970.tre,
  EricsonStage2Full_9965.tre, EricsonStage2Full_1135.tre, EricsonStage2Full_4445.tre,
  EricsonStage2Full_7665.tre, EricsonStage2Full_9127.tre, EricsonStage2Full_1847.tre,
  EricsonStage2Full_7104.tre, EricsonStage2Full_6356.tre, EricsonStage2Full_3698.tre,
  EricsonStage2Full_2923.tre, EricsonStage2Full_5038.tre, EricsonStage2Full_6762.tre,
  EricsonStage2Full_8902.tre, EricsonStage2Full_3398.tre, EricsonStage2Full_2799.tre,
  EricsonStage2Full_1951.tre, EricsonStage2Full_0140.tre, EricsonStage2Full_0537.tre,
  EricsonStage2Full_0471.tre, EricsonStage2Full_5694.tre, EricsonStage2Full_4453.tre,
  EricsonStage2Full_9205.tre, EricsonStage2Full_7977.tre, EricsonStage2Full_0690.tre,
  EricsonStage2Full_1551.tre, EricsonStage2Full_4141.tre, EricsonStage2Full_2174.tre,
  EricsonStage2Full_2170.tre, EricsonStage2Full_1993.tre, EricsonStage2Full_0629.tre,
  EricsonStage2Full_5578.tre]
status: COMPLETED
created_at: "2022-02-28T17:35:30Z"
completed_at: "2022-02-28T17:36:24Z"
bad_names: {EricsonStage2Full_0039.tre: [], EricsonStage2Full_0059.tre: [], EricsonStage2Full_0130.tre: [],
  EricsonStage2Full_0140.tre: [], EricsonStage2Full_0188.tre: [], EricsonStage2Full_0259.tre: [],
  EricsonStage2Full_0301.tre: [], EricsonStage2Full_0431.tre: [], EricsonStage2Full_0471.tre: [],
  EricsonStage2Full_0537.tre: [], EricsonStage2Full_0629.tre: [], EricsonStage2Full_0690.tre: [],
  EricsonStage2Full_0772.tre: [], EricsonStage2Full_0782.tre: [], EricsonStage2Full_1135.tre: [],
  EricsonStage2Full_1313.tre: [], EricsonStage2Full_1515.tre: [], EricsonStage2Full_1551.tre: [],
  EricsonStage2Full_1614.tre: [], EricsonStage2Full_1662.tre: [], EricsonStage2Full_1776.tre: [],
  EricsonStage2Full_1847.tre: [], EricsonStage2Full_1863.tre: [], EricsonStage2Full_1891.tre: [],
  EricsonStage2Full_1951.tre: [], EricsonStage2Full_1956.tre: [], EricsonStage2Full_1993.tre: [],
  EricsonStage2Full_2024.tre: [], EricsonStage2Full_2170.tre: [], EricsonStage2Full_2174.tre: [],
  EricsonStage2Full_2206.tre: [], EricsonStage2Full_2309.tre: [], EricsonStage2Full_2752.tre: [],
  EricsonStage2Full_2789.tre: [], EricsonStage2Full_2799.tre: [], EricsonStage2Full_2923.tre: [],
  EricsonStage2Full_2948.tre: [], EricsonStage2Full_2979.tre: [], EricsonStage2Full_3081.tre: [],
  EricsonStage2Full_3111.tre: [], EricsonStage2Full_3172.tre: [], EricsonStage2Full_3276.tre: [],
  EricsonStage2Full_3398.tre: [], EricsonStage2Full_3434.tre: [], EricsonStage2Full_3505.tre: [],
  EricsonStage2Full_3698.tre: [], EricsonStage2Full_3793.tre: [], EricsonStage2Full_3880.tre: [],
  EricsonStage2Full_4017.tre: [], EricsonStage2Full_4141.tre: [], EricsonStage2Full_4322.tre: [],
  EricsonStage2Full_4346.tre: [], EricsonStage2Full_4380.tre: [], EricsonStage2Full_4445.tre: [],
  EricsonStage2Full_4453.tre: [], EricsonStage2Full_4613.tre: [], EricsonStage2Full_4870.tre: [],
  EricsonStage2Full_4991.tre: [], EricsonStage2Full_5038.tre: [], EricsonStage2Full_5073.tre: [],
  EricsonStage2Full_5435.tre: [], EricsonStage2Full_5578.tre: [], EricsonStage2Full_5694.tre: [],
  EricsonStage2Full_5714.tre: [], EricsonStage2Full_5995.tre: [], EricsonStage2Full_6356.tre: [],
  EricsonStage2Full_6513.tre: [], EricsonStage2Full_6575.tre: [], EricsonStage2Full_6577.tre: [],
  EricsonStage2Full_6591.tre: [], EricsonStage2Full_6762.tre: [], EricsonStage2Full_6782.tre: [],
  EricsonStage2Full_6830.tre: [], EricsonStage2Full_6839.tre: [], EricsonStage2Full_6842.tre: [],
  EricsonStage2Full_6919.tre: [], EricsonStage2Full_7070.tre: [], EricsonStage2Full_7104.tre: [],
  EricsonStage2Full_7419.tre: [], EricsonStage2Full_7628.tre: [], EricsonStage2Full_7633.tre: [],
  EricsonStage2Full_7634.tre: [], EricsonStage2Full_7665.tre: [], EricsonStage2Full_7893.tre: [],
  EricsonStage2Full_7977.tre: [], EricsonStage2Full_8010.tre: [], EricsonStage2Full_8050.tre: [],
  EricsonStage2Full_8500.tre: [], EricsonStage2Full_8806.tre: [], EricsonStage2Full_8869.tre: [],
  EricsonStage2Full_8902.tre: [], EricsonStage2Full_9116.tre: [], EricsonStage2Full_9127.tre: [],
  EricsonStage2Full_9205.tre: [], EricsonStage2Full_9613.tre: [], EricsonStage2Full_9660.tre: [],
  EricsonStage2Full_9703.tre: [], EricsonStage2Full_9767.tre: [], EricsonStage2Full_9965.tre: [],
  EricsonStage2Full_9970.tre: []}
